{
    "openapi": "3.0.0",
    "info": {
        "title": "API Server",
        "version": "0.1"
    },
    "servers": [
        {
            "url": "http://localhost:8080/api",
            "description": "Mon API"
        }
    ],
    "paths": {
        "/servers": {
            "get": {
                "parameters": [
                    {
                        "name": "id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Liste des serveurs par id",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Page not found (serveur non trouvé)",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "operationId": "App\\Controllers\\ServerController::putServer",
                "parameters": [
                    {
                        "name": "id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Modifier un serveur",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Des champs sont vides",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "operationId": "App\\Controllers\\ServerController::postServer",
                "responses": {
                    "200": {
                        "description": "Créer un serveur",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Des champs sont vides",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "operationId": "App\\Controllers\\ServerController::deleteServer",
                "parameters": [
                    {
                        "name": "id",
                        "in": "query",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Supprimer un serveur",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/users": {
            "put": {
                "operationId": "App\\Controllers\\UserController::putUser",
            "parameters":
                in: body
                name: user
                description: The user to create.
                schema:
                    type: object
                    required:
                    - [login,passwod]
                    properties:
                    login:
                        type: string
                    password:
                        type: string
                "responses": {
                    "200": {
                        "description": "Modification du profil",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}